# Generated by Django 2.2.26 on 2022-01-10 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='property_address',
            new_name='address',
        ),
    ]
